### ISSUE TITLE
Best practices when running TurtleCoind & walletd daemon

### ISSUE THREAD

**Issue by fexra** [turtlecoin/meta#68]
As our community is growing, development is too. Many people, including myself, have been building tools and apps on the TRTL protocol for a few weeks now. At this stage, I have reached the point where I will be needing to run the TurtleCoind daemon and the walletd daemon in the background on a server, consistently. I been doing some research, and wanted to share with what I been testing out, and was hoping for others to give input and share their thoughts and opinions on this matter.

At the moment I been running both daemons successfully in the background for a week on an Ubuntu server without interruption with the following code:

`./walletd -w wallet -p password --rpc-password password --hide-my-port --daemon --bind-address localhost`

`nohup ./TurtleCoind > /dev/null 2>&1 &`

This seems to work fine. If you would want to save the logs change > /dev/null to  a destination. 

A better solution, recommended by @ZedPea , would be to run both daemons are services. This would allow you to easily start, restart, and stop them (in theory) as with the above lines of code the only way would be to reboot your server. I would like to explore this idea, but never worked with systemd before. What would the stop and restart commands be, and is there a better way to pass arguments?

Here is what madk came up with:

turtlecoind.service
```
[Unit]
Description=Starts the turtlecoind service and monitors for crashes

[Service]
Environment="SCRIPT_ARGS=%I"
WorkingDirectory=/home/user/turtlecoin-data/ # dir containing turtlecoin and wallets etc.
ExecStart=/home/user/Turtlecoin/TurdleCoind
```

walletd.service
```
[Unit]
Description=Starts the turtlecoin wallet service and monitors for crashes
After=turtlecoind.service

[Service]
User=user
WorkingDirectory=/home/user/turtlecoin-data/ # dir containing turtlecoin and wallets etc.
ExecStart=/home/user/Turtlecoin/walletd -w walletfile.bin -p $WALLETPASS --rpc-password=$RPC_PASS --local 
Restart=on-failure
```
Then run `sudo systemctl edit walletd` and put this as contents:
```
[Service]
Environment="RPC_PASS=yourpassword"
Environment="WALLETPASS =yourpassword"
```

[Overview of systemd options](https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files)

Some other practices (for an app) I think that should be discussed:

- Should you announce your port?
- Should you change your port?
- You could put a firewall in front of the daemons and only allow local connection.

**Comment by Tom7003** [comment]
> Should you announce your port?

yes

> Should you change your port?

probably not unless you need to because there is something else using it

> You could put a firewall in front of the daemons and only allow local connection.

block the json-rpc port default tcp/11898 but try to leave the p2p port open, this is better for you and the network as you will get faster updates, push them out faster I think.

Also add a dependancy to start it after the network is available ;)

```
[Unit]
Description=Starts the turtlecoind service and monitors for crashes
After=network.target

[Service]
Environment="SCRIPT_ARGS=%I"
WorkingDirectory=/home/user/turtlecoin-data/ # dir containing turtlecoin and wallets etc.
ExecStart=/home/user/Turtlecoin/TurdleCoind
```

I run turtlecoind under k8s with probes to determine if the needed service is responding on the json-rpc port. As follows, the docker image I used is based on the one in the main repo.

replace <items> with ones specific to your deployment. This runs 2 daemon instances behind a load balancer.

```
apiVersion: v1
kind: Service
metadata:
  name: turtlecoind-prod-v18
  labels:
    app: turtlecoind-prod
spec:
  ports:
  - port: 11898
    name: jsonrpc
  type: LoadBalancer
  selector:
    app: turtlecoind-prod-v18
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: turtlecoind-prod-v18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: turtlecoind-prod-v18
  template:
    metadata:
      labels:
        app: turtlecoind-prod-v18
    spec:
      hostNetwork: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - turtlecoind-prod-v18
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: turtlecoind-prod-v18
        imagePullPolicy: Always
        image: <myturtlecoind image>
        ports:
        - containerPort: 11898
          protocol: TCP
          name: jsonrpc
        - containerPort: 11897
          hostPort: 11897
          protocol: TCP
          name: p2p
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /json_rpc
            port: 11898
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /json_rpc
            port: 11898
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 60
          successThreshold: 2
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 200m
        volumeMounts:
        - mountPath: /var/lib/turtlecoind
          name: local-ssd
      volumes:
      - name: "local-ssd"
        hostPath:
          path: "</mnt/yourpath>"
```
